### Train model in notebook (inefficient, for testing and debug only)

In [1]:
import os

In [ ]:
#os.environ['NCCL_DEBUG'] = 'INFO'
#os.environ['NCCL_DEBUG_SUBSYS'] = 'ALL'
#os.environ['TORCH_DISTRIBUTED_DEBUG'] = 'INFO'
os.environ['NCCL_IB_DISABLE'] = '1'
os.environ['NCCL_SOCKET_IFNAME'] = 'enp2s0f1np1'
os.environ['NCCL_P2P_DISABLE'] = '1'
os.environ['NCCL_BLOCKING_WAIT'] = '1'

In [1]:
import sys
from os.path import join
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch import optim, nn
import torch.multiprocessing as mp
from torch.distributed import init_process_group, destroy_process_group
from torch.utils.data.distributed import DistributedSampler
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader
from astropy.io import fits
import pyxis.torch as pxt
import normflows as nf

from networks import *
from train import *
import config

train_dir = '/ocean/projects/phy250048p/shared/datasets/test_1m_low_hlr'
test_dir = '/ocean/projects/phy250048p/shared/datasets/test_1m_low_hlr'
fig_dir = '/ocean/projects/phy250048p/shared/figures/'
model_dir = '/ocean/projects/phy250048p/shared/models/'

In [2]:
torch.cuda.device_count()

1

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
world_size = 1
save_every = 1
nepochs = config.train['epoch_number']
batch_size = config.train['batch_size']
nfeatures = config.train['feature_number']

In [5]:
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "12355"
torch.cuda.set_device(0)
init_process_group(backend='nccl', rank=0, world_size=1)

In [6]:
train_ds = pxt.TorchDataset(train_dir)
valid_ds = pxt.TorchDataset(test_dir)

In [7]:
x = torch.unsqueeze(train_ds[0]['img'], 1)
print(x.shape)

torch.Size([1, 1, 48, 48])


In [8]:
norm_x = nn.functional.normalize(x, dim=[2,3])

In [9]:
model = ForkCNN(mode=1)
model.to(0)
model = DDP(model, device_ids=[0])

In [10]:
print(model)

DistributedDataParallel(
  (module): ForkCNN(
    (img_net): ImgCNN(
      (cnn_img): Sequential(
        (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
        (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): ReLU(inplace=True)
        (6): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
        (7): ResidualBlock(
          (cnn1): Sequential(
            (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU(inplace=True)
          )
          (cnn2): Sequential(
            (0): Conv2d(128, 128, kernel_size=(3, 3),

In [11]:
# optimizer = optim.SGD(model.parameters(), 
#                       lr=config.train['initial_learning_rate'],
#                       momentum=config.train['momentum'])
optimizer = optim.AdamW(model.parameters(),
                        lr=config.train['initial_learning_rate'], 
                        weight_decay=config.train['weight_decay'])

In [12]:
trainer = CNNTrainer(world_size, model, nfeatures, train_ds, valid_ds, optimizer, 0, save_every, batch_size)

In [13]:
trainer.train(2)

KeyboardInterrupt: 

In [6]:
destroy_process_group()

AssertionError: 

In [5]:
mp.spawn(train_nn, args=(world_size, ForkCNN, CNNTrainer), nprocs=world_size)

INFO:Setup:Initializing
INFO:Setup:[rank: 0] Successfully set up device
INFO:Setup:Loaded new model CNN-CNN-flow_all_params
INFO:Setup:[rank: 0] Successfully loaded training objects
INFO:Setup:[rank: 0] Successfully initialized Trainer
/jet/home/xwang30/.conda/envs/kl-nn/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:4876: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  warnings.warn(  # warn only once
INFO:Trainer:Setting up tensors on GPU
INFO:Trainer:Uploading training set to GPU...
INFO:Trainer:10% complete
INFO:Trainer:20% complete
INFO:Trainer:30% complete
INFO:Trainer:40% complete
INFO:Trainer:50% complete
INFO:Trainer:60% complete
INFO:Trainer:70% complete
INFO:Trainer:80% complete
INFO:Trainer:90% complete
INFO:Trainer:Uploading validation set to GPU...
INFO:Trainer:10% complete
INFO:Trainer:20% complete
INFO:Trainer:30% complete
INFO:Trainer:40% complete
INFO:Traine

torch.Size([100, 1, 48, 48])
tensor([20.1792, 11.8893,  1.4887,  6.0030, 16.3536, 28.4925, 36.9552,  7.6818,
        14.0914,  1.4356, 12.7547,  0.7539,  2.8140,  4.2396,  1.5966,  3.3511,
         8.0732, 10.1641, 13.8984, 13.7916, 12.4427,  1.9673,  2.9536, 35.0477,
         2.4491, 10.8532, 13.2279, 11.2593, 21.4432,  2.8719,  4.5393, 30.3814,
         6.6178,  0.5115,  1.7364, 11.6314,  4.8490, 10.7021,  5.3050, 23.8975,
        10.8650, 13.5197,  1.9421,  9.7638, 13.3832, 18.9935,  4.3853, 32.3961,
         2.8398,  4.3034,  1.1613, 10.2020, 12.5481,  3.8575, 33.8791,  0.1906,
        22.8450, 15.0862, 24.8522, 10.8177,  7.2854,  4.8814, 25.3125, 11.8861,
         6.2978, 11.8032,  5.3621,  7.8338, 26.8547,  6.8643,  4.9916, 10.7634,
         1.4568,  0.6484,  2.6392,  3.5395,  2.9671,  0.5920, 34.3919,  0.4715,
         6.1753,  5.9978,  1.0380,  0.2874,  0.9764, 15.7969,  6.7360, 20.6084,
         5.7696,  2.7996,  9.7481,  9.5977,  0.4572,  3.3285,  1.1871,  7.1646,
        21.

INFO:Trainer:Batch 100 complete


tensor([15.7146,  3.9541, 13.7959,  2.2516,  9.8399,  0.3262,  0.7845,  1.0232,
         1.4543,  2.3562,  9.5498,  2.6664,  8.9850,  4.1970,  0.4502,  2.9880,
         9.1350,  0.4259,  4.8266,  0.7248,  3.9208,  2.7070,  1.5893,  0.1844,
         1.2107,  5.7302,  0.6878,  2.8836,  1.1305, 15.2282,  2.6520,  0.1700,
         5.1129, 13.3969, 11.4956,  4.1062,  1.6914,  1.4355,  0.2238,  3.9372,
         3.8126,  8.1778,  2.6176,  0.4763, 10.9554,  1.4245,  0.6234, 10.4016,
        14.3004,  3.8894,  0.7191, 13.3553,  0.2917,  1.5696,  0.1419,  0.2250,
         2.7421,  6.5477,  2.7585,  1.3635, 14.4026,  3.2795,  1.1824,  8.3606,
         4.4641, 12.4425,  0.8004,  3.7420,  5.7985,  7.4648, 12.8191, 12.6233,
         8.3912,  8.7946,  1.0438,  2.8079,  1.0804,  0.0662,  4.4351,  0.5542,
        11.9867, 19.9543, 14.7605,  9.1027,  1.9434,  0.1885,  1.2219,  1.2810,
         3.6225,  0.6101,  0.8461,  1.0058,  3.0320,  5.0381,  4.1458,  0.1433,
         0.5501,  0.1077,  0.5353,  3.09

INFO:Trainer:Batch 200 complete


tensor([ 2.0599,  1.4103, 14.2468, 12.6586,  4.0747,  3.1998, 11.2458,  4.6051,
         2.5500,  1.3716,  8.1165, 14.9316,  2.2190,  0.1712,  2.9589,  5.5960,
         0.5812,  0.3548,  5.2149,  2.1241,  1.9950,  3.6281,  1.7459,  6.0960,
         2.4387,  3.7681,  5.1081,  8.9154, 11.9044,  3.4441,  0.8609,  2.8629,
         5.3596,  9.2521,  3.3092,  2.0565,  9.4463,  7.9191,  2.5127,  0.7278,
         2.9025,  6.5104,  1.3575,  9.8107,  0.7990,  9.1496,  9.1505,  4.3188,
        14.4507,  3.6286,  0.9330,  1.9641,  5.0198,  1.6656,  5.5537, 15.0011,
         8.8897, 11.8032,  2.0887,  3.4680, 15.0561, 14.0147,  9.4513,  3.3167,
         9.0701,  7.6750,  0.7021, 10.2356,  6.4946,  5.7352,  6.0839,  4.3047,
         7.3652,  6.4205,  1.2187, 13.0395, 11.4716,  2.6221,  2.1547,  1.0806,
        16.4786, 12.5354, 11.7268,  0.2906,  2.8726,  2.2075,  5.3191,  9.2936,
         1.5907,  1.3578,  0.5500,  1.9286,  1.9797,  2.6055,  4.6707,  5.3527,
         4.7899,  2.2905,  2.4248,  6.72

INFO:Trainer:Batch 300 complete


tensor([ 5.1470,  1.4153, 24.6353,  0.2807,  7.0975,  4.0645, 11.4520,  9.6356,
        10.8226, 11.6545,  0.4018,  9.3968,  8.9174, 28.6296,  0.4226,  0.2600,
        12.3573,  1.4432,  5.7043, 17.9328,  0.4370, 17.4321,  1.5955,  1.1201,
        19.3567, 25.8218,  9.2178,  7.7109,  9.0899,  4.7143,  3.2476,  1.5105,
         4.7845,  5.6047,  6.1868,  2.9802,  1.4282,  3.4577, 10.7992,  3.4055,
         0.6312,  4.3104, 41.0757,  4.1251,  9.9448,  3.5892, 14.2248, 29.5012,
         5.9593, 15.4855,  7.7968,  4.2340, 10.1765,  7.4006,  2.3113, 17.6961,
         0.9037, 14.8530,  6.8896,  9.5694, 17.0285,  1.1163,  8.0482,  8.4148,
         1.0243, 22.5104,  7.6962,  4.3356, 12.4093, 21.1944,  2.7629,  0.6379,
         0.3734, 15.4454, 13.4042,  2.5730,  8.5052,  0.6779,  3.7202,  2.5450,
         1.7495, 27.8185, 27.4645, 10.2455,  2.7613, 17.2084, 19.3899,  1.1675,
        11.7687,  4.0280, 11.5006,  0.1133,  9.3525,  1.0384, 14.1227, 10.0285,
        14.5495,  5.0355,  1.4256,  0.74

KeyboardInterrupt: 

tensor([ 1.3402,  7.9686,  0.6545,  1.7108,  0.1920,  8.8123,  3.1632,  8.3857,
         7.9087, 11.3221, 10.7551,  1.6330,  2.9378, 11.9405, 11.9683,  5.8456,
         0.4242,  0.5084,  0.1509,  3.6024,  8.3080,  7.2283,  4.0023,  0.8863,
         0.8673,  1.6578,  4.6830, 14.8036,  2.4039, 12.4883,  7.3125,  1.5446,
         0.4837, 10.3082,  0.3792,  4.8610,  0.4358,  2.2208,  1.7387,  6.7655,
         0.4223, 13.1427,  0.2659,  5.0202, 11.5078,  2.4494,  4.1116,  2.1934,
         0.9655,  2.1829,  0.6751,  9.0009,  0.6867,  4.8275,  5.6877,  7.9500,
         2.4000, 12.7477,  6.3011,  0.2712,  8.9211,  4.3148, 10.9260,  0.7529,
         0.3561,  1.9512,  3.7091,  0.6961,  0.3752,  1.7031,  0.8283,  2.5061,
         9.2332, 13.2327,  1.8302,  1.4868,  2.3931,  0.1944,  1.1405,  0.4747,
         2.2830,  2.3312,  9.9239,  0.3198,  1.8388,  7.4789,  8.1539, 13.5124,
        14.8061,  0.1616,  5.8462,  1.2219,  6.9541, 11.6310,  1.0793,  0.3950,
         5.1842,  0.7241,  0.6520,  7.27

[rank0]:[W427 14:01:22.085521961 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
